---
title: "Formating Fence GPS points"
author: "Brandon Mayer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(smoothr)

world <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r}
# Enter base path where folders containing RAW and processed are located
path <- paste(dirname(path.expand('~')),"/Box/1.Ruyle_lab/1.Project_Data/Virtual Fencing/", sep="")

# Identify files that need to be processed
filelist <-list.files(paste0(path,"RAWFenceFolder"),pattern = ".txt", full.names = T, all.files = TRUE, recursive = TRUE); filenames <- stringr::str_replace_all(basename(filelist),".txt","")
endlist <- stringr::str_replace_all(list.files(paste0(path,"ProcessedFences"),pattern = ".csv"),".csv","")
VAP <-rbind(read_csv(paste0(path,"VencePCPeriods.csv")),read_csv(paste0(path,"VenceSPPeriods.csv")))
NeedProcessing <- setdiff(VAP$Fence[!is.na(VAP$Off)],endlist);(paste("Listed fences have incomplete `fence off` dates:",VAP$Fence[is.na(VAP$Off)]))
if (length(NeedProcessing)>0) {
  filelist <- filelist[grepl(paste(NeedProcessing, collapse = "|"), filenames)]
}

# Load in relevant data associated with the virtual fence
for (i in 1:length(filelist)) {
  x <- read.table( filelist[i], sep=",", header=TRUE)
  x$Fence <- stringr::str_remove(basename(filelist[i]),".txt")
  x <- x %>% left_join(VAP,by = "Fence")
  write.csv(x, file = paste0(stringr::str_replace(paste0(path,"ProcessedFences/",basename(filelist[i])),".txt",".csv")),row.names = F)
}
(endlist <- list.files(paste0(path,"ProcessedFences"),pattern = ".csv", full.names = T, all.files = TRUE, recursive = TRUE) %>%
  lapply(function(x) {read.csv(x)}))
```

```{r,message=FALSE}
for (j in 1:length(endlist)) {
test <- endlist[[j]] %>% filter(!is.na(Fgroup))%>% select(Fgroup,latitude, longitude, Shock, Sound) %>% group_by(Fgroup)%>% mutate(points = seq(1:length(latitude)))
meta <- endlist[[j]] %>% filter(!is.na(Fgroup))%>% select(Fgroup,Fence, Herd, On, Off) %>% group_by(Fence, Herd, On, Off) %>% summarise()
FencePoints<- st_as_sf(test, coords = c("longitude", "latitude"), 
    crs = 4326)
FencePoints <- FencePoints%>% group_by(Fgroup) %>% group_split()
Fullfence <- list();FullBufferSh <- list();FullBufferSo <- list()

FullFenceShape<- st_as_sf(endlist[[j]], coords = c("longitude", "latitude"),
    crs = 4326) %>% st_cast("POINT")%>% st_combine()%>% st_cast("POLYGON")

for (i in 1:length(FencePoints)) {

# lapply(list, function)
points <- st_cast(st_geometry(FencePoints[[i]]), "POINT") 
# Number of total linestrings to be created
n <- length(points) - 1
# Build linestrings
linestrings <- lapply(X = 1:n, FUN = function(x) {
  pair <- st_combine(c(points[x], points[x + 1]))
  line <- st_cast(pair, "LINESTRING")
  return(line)

})

# One MULTILINESTRING object with all the LINESTRINGS
multilinetring <- st_multilinestring(do.call("rbind", linestrings))
as.data.frame(points)
multilinetring <- st_sfc(multilinetring,crs = 4326)
Fullfence[i] <- multilinetring
# one linestringsbuffers object with all buffers
bufferrawSh <- st_buffer(multilinetring,
                       dist = unique(test$Shock))
bufferrawSo <- st_buffer(multilinetring,
                       dist = unique(test$Shock)+unique(test$Sound))
bufferSh <- smooth(bufferrawSh, method = "ksmooth", smoothness = 10,)
bufferSo <- smooth(bufferrawSo, method = "ksmooth", smoothness = 10,)

buffersSo <-st_difference(bufferSo,bufferSh)
FinalVFSo<- st_intersection(buffersSo,FullFenceShape)
FinalVFSh<- st_intersection(bufferSh,FullFenceShape)

FullBufferSh[i] <-FinalVFSh;FullBufferSo[i] <-FinalVFSo
}
# # Calculate the maximum of nearest neighbor distances (in km)

# Create a polygon = MCP + buffer
#sf_use_s2(T)

FulllinestringsbuffersSh <- st_multipolygon(FullBufferSh);FulllinestringsbuffersSo <- st_multipolygon(FullBufferSo)
FulllinestringsbuffersSh <- st_sfc(FulllinestringsbuffersSh,crs = 4326);FulllinestringsbuffersSo <- st_sfc(FulllinestringsbuffersSo,crs = 4326)

Herd <- unique(endlist[[j]]$Herd);Fence<-unique(endlist[[j]]$Fence)
st_write(FullFenceShape %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_FF.shp"));st_write(FulllinestringsbuffersSo %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_Sound.shp"));st_write(FulllinestringsbuffersSh %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_Shock.shp"))
print(ggplot(data = world) +
    geom_sf() +
    geom_sf(data = FullFenceShape)+
    geom_sf(data = FulllinestringsbuffersSh) +
    geom_sf(data = FulllinestringsbuffersSo)+
coord_sf(xlim = c(max(endlist[[j]]$longitude)+.01, min(endlist[[j]]$longitude)-.01), ylim = c(min(endlist[[j]]$latitude)-.01, max(endlist[[j]]$latitude)+.01), expand = FALSE))
#readline(prompt="Press [enter] to continue")

}


```

