---
title: "Formating Fence GPS points"
author: "Brandon Mayer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(smoothr)

world <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r}
# Enter base path where folders containing RAW and processed are located
path <- paste(dirname(path.expand('~')),"/Box/1.Ruyle_lab/1.Project_Data/Virtual Fencing/", sep="")

# Identify files that need to be processed
filelist <-list.files(paste0(path,"RAWFenceFolder"),pattern = ".txt", full.names = T, all.files = TRUE, recursive = TRUE); filenames <- stringr::str_replace_all(basename(filelist),".txt","")
endlist <- stringr::str_replace_all(list.files(paste0(path,"ProcessedFences"),pattern = ".csv"),".csv","")
VAP <-rbind(read_csv(paste0(path,"VencePCPeriods.csv")),read_csv(paste0(path,"VenceSPPeriods.csv")))
NeedProcessing <- setdiff(VAP$Fence[!is.na(VAP$Off)],endlist);(paste("Listed fences have incomplete `fence off` dates:",VAP$Fence[is.na(VAP$Off)]))

if (length(NeedProcessing)>0) {
  filelist <- filelist[grepl(paste(NeedProcessing, collapse = "|"), filenames)]
}

# Load in relevant data associated with the virtual fence
if (length(filelist)>0) {
  for (i in 1:length(filelist)) {
  x <- read.table( filelist[i], sep=",", header=TRUE)
  x$Fence <- stringr::str_remove(basename(filelist[i]),".txt")
  VAPclean <- VAP[!is.na(VAP$Off),] 
  VAPcleanSplit <- VAPclean %>% split(VAPclean$Herd)
  for (h in 1:length(VAPcleanSplit)) {
    for (f in 1:length(unique(VAPcleanSplit[[h]]$Fence))) {
      x1<- x
      x1 <- x1 %>% left_join(VAPcleanSplit[[h]][f,],by = "Fence")
      if (!is.na(unique(x1$Herd))) {
        write.csv(x1, file = paste0(stringr::str_replace(paste0(path,"ProcessedFences/",unique(x1$Herd),"_",basename(filelist[i])),".txt",".csv")),row.names = F)
      }
     }
    }
  }
}
# List of files that can be converted to fence shapefiles
Endlist <- list.files(paste0(path,"ProcessedFences"),pattern = ".csv",full.names = T)

# (list.files(paste0(path,"ProcessedFences"),pattern = ".csv", full.names = T, all.files = TRUE, recursive = TRUE) %>%
#   lapply(function(x) {read.csv(x)}))
```

```{r,message=FALSE}
Processed <- stringr::str_replace_all(list.files(paste0(path,"ProcessedFences"),pattern = ".csv", full.names = F, all.files = TRUE, recursive = TRUE),".csv","")
Shapefiles <- stringr::str_split(stringr::str_replace_all(list.files(paste0(path,"Shapefiles"),pattern = ".shp", full.names = F, all.files = TRUE, recursive = TRUE),".shp",""), "_") %>% sapply(., "[[", 2) %>% unique()

NeedProcessing <- setdiff(Processed,Shapefiles)
if (length(NeedProcessing)>0) {
  endlist <- Endlist[grepl(paste(NeedProcessing, collapse = "|"), Processed)]%>%
  lapply(function(x) {read.csv(x)})
}

j<-8
for (j in 1:length(endlist)) {
test <- endlist[[j]] %>% filter(!is.na(Fgroup))%>% select(Fgroup,latitude, longitude, Shock, Sound) %>% group_by(Fgroup)%>% mutate(points = seq(1:length(latitude)))
meta <- endlist[[j]] %>% filter(!is.na(Fgroup))%>% select(Fgroup,Fence, Herd, On, Off) %>% group_by(Fence, Herd, On, Off) %>% summarise()
FencePoints<- st_as_sf(test, coords = c("longitude", "latitude"),
    crs = 4326)

FencePoints <- FencePoints%>% group_by(Fgroup) %>% group_split()
Fullfence <- list();FullBufferSh <- list();FullBufferSo <- list()

FullFenceShape<- st_as_sf(endlist[[j]], coords = c("longitude", "latitude"),
    crs = 4326) %>% st_cast("POINT")%>% st_combine()%>% st_cast("POLYGON")

for (i in 1:length(FencePoints)) {

# lapply(list, function)
points <- st_cast(st_geometry(FencePoints[[i]]), "POINT") 
# Number of total linestrings to be created
n <- length(points) - 1
# Build linestrings
linestrings <- lapply(X = 1:n, FUN = function(x) {
  # pair <- st_combine(c(points[x], points[x + 1]))
  # line <- st_union(pair)
  line <- st_union(c(points[x], points[x + 1]))
  line <- st_cast(line, "LINESTRING") # potential issue with casting points to a line
  return(line)

})

# One MULTILINESTRING object with all the LINESTRINGS
multilinetring <- st_multilinestring(do.call("rbind", linestrings))
multilinetring <- st_sfc(multilinetring,crs = 4326)
Fullfence[i] <- multilinetring
plot(multilinetring)
# one linestringsbuffers object with all buffers
bufferrawSh <- st_buffer(multilinetring,
                       dist = unique(test$Shock))
bufferrawSo <- st_buffer(multilinetring,
                       dist = unique(test$Shock)+unique(test$Sound))
# attmepting to use rgeos and sp
rgeostrial<- rgeos::gBuffer(as(multilinetring,Class = "Spatial"),width = unique(test$Shock),capStyle="SQUARE")
rgeostrial <-sp::spTransform( rgeostrial, sp::CRS( "+init=epsg:4326" ) ) 
plot(st_as_sf(rgeostrial,crs = 4326))


# Removed the smothing to see if st_union would change the buffer resolution
# bufferSh <- smooth(densify(bufferrawSh, max_distance = 10), method = "ksmooth", smoothness = 18,)
# bufferSo <- smooth(densify(bufferrawSo, max_distance = 10), method = "ksmooth", smoothness = 18,)
bufferSh <- bufferrawSh
bufferSo <- bufferrawSo

buffersSo <-st_difference(bufferSo,bufferSh)
FinalVFSo<- st_intersection(buffersSo,FullFenceShape)
FinalVFSh<- st_intersection(bufferSh,FullFenceShape)
plot(FinalVFSh)
plot(FinalVFSo)
FullBufferSh[i] <-FinalVFSh;FullBufferSo[i] <-FinalVFSo
}


FulllinestringsbuffersSh <- st_multipolygon(FullBufferSh);FulllinestringsbuffersSo <- st_multipolygon(FullBufferSo)
FulllinestringsbuffersSh <- st_sfc(FulllinestringsbuffersSh,crs = 4326);FulllinestringsbuffersSo <- st_sfc(FulllinestringsbuffersSo,crs = 4326)

Herd <- unique(endlist[[j]]$Herd);Fence<-unique(endlist[[j]]$Fence)
st_write(FullFenceShape %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_FF.shp"));st_write(FulllinestringsbuffersSo %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_Sound.shp"));st_write(FulllinestringsbuffersSh %>% merge(meta),paste0(path,"Shapefiles/",Herd,"_",Fence,"_Shock.shp"))
print(ggplot(data = world) +
    geom_sf() +
    geom_sf(data = FullFenceShape)+
    geom_sf(data = FulllinestringsbuffersSh) +
    geom_sf(data = FulllinestringsbuffersSo)+
coord_sf(xlim = c(max(endlist[[j]]$longitude)+.01, min(endlist[[j]]$longitude)-.01), ylim = c(min(endlist[[j]]$latitude)-.01, max(endlist[[j]]$latitude)+.01), expand = FALSE))
#readline(prompt="Press [enter] to continue")

}


```
Select the virtual herd from VAP and period of observation.  
```{r}
VAP <-rbind(read_csv(paste0(path,"VencePCPeriods.csv")),read_csv(paste0(path,"VenceSPPeriods.csv")))
# reticulate::use_python("C:/Users/brand/anaconda3/python.exe")
# reticulate::use_virtualenv("Vence-API")
<- read.csv("C:/Users/brand/PycharmProjects/Vence-API/data/2022-12-19_2022-12-21_Vence-message-data.csv")

```

